xen/xenfs: build privcmd for domU now that it is exposed
Fixes build error introduced in 66d850da "xen/privcmd: make privcmd
visible in domU"

drivers/built-in.o:(.data+0xd44): undefined reference to `privcmd_file_ops'
make[1]: *** [.tmp_vmlinux1] Error 1
make: *** [sub-make] Error 2

Signed-off-by: Ian Campbell <ian.campbell@citrix.com>
Signed-off-by: Jeremy Fitzhardinge <jeremy.fitzhardinge@citrix.com>