x86/hpet: fix build error with CONFIG_HPET_TIMER=n
    In file included from arch/x86/kernel/time_32.c:38:
    arch/x86/include/asm/hpet.h: In function 'disable_hpet':
    arch/x86/include/asm/hpet.h:111: error: parameter name omitted
    make[3]: *** [arch/x86/kernel/time_32.o] Error 1
    make[3]: *** Waiting for unfinished jobs....
    make[2]: *** [arch/x86/kernel] Error 2
    make[2]: *** Waiting for unfinished jobs....

Caused by:
    commit b2a93181340b2efd58f16a2d7303f6f45591bca0
    Author: Wei Gang <gang.wei@intel.com>
    Date:   Sun Oct 18 17:39:04 2009 +0900

        x86/hpet: allow hpet to be programmatically disabled

Signed-off-by: Ian Campbell <ian.campbell@citrix.com>
Cc: Wei Gang <gang.wei@intel.com>
Cc: Jeremy Fitzhardinge <jeremy.fitzhardinge@citrix.com>