xen-pcifront: Fix compile error: implicit declaration of function 'gnttab_end_foreign_access'
The function in question now resides in grant-table.h instead of gnttab.h.
Fixed the include file decleration.

Signed-off-by: Konrad Rzeszutek Wilk <konrad.wilk@oracle.com>
Signed-off-by: Jeremy Fitzhardinge <jeremy.fitzhardinge@citrix.com>